#!/usr/bin/env python3
"""
Extract one "Bezier slower despite fewer steps" instance from eval_per_instance.jsonl.gz.

Outputs a Julia include file that defines:
  DEGREE::Int
  BEZIER_DEGREE::Int
  START_COEFFS::Vector{ComplexF64}
  TARGET_COEFFS::Vector{ComplexF64}
  GAMMA::ComplexF64
  BEZIER_CTRL::Matrix{ComplexF64}

Usage:
  python3 extract_problem_instance.py \
    --input results/.../eval_per_instance.jsonl.gz \
    --output /tmp/case.jl \
    --mode best
"""

from __future__ import annotations

import argparse
import gzip
import json
from pathlib import Path


def _cplx(v: list[float]) -> complex:
    return complex(float(v[0]), float(v[1]))


def _to_vec(vals: list[list[float]]) -> list[complex]:
    return [_cplx(v) for v in vals]


def _to_mat(vals: list[list[list[float]]]) -> list[list[complex]]:
    return [[_cplx(v) for v in row] for row in vals]


def _julia_complex(z: complex) -> str:
    return f"({z.real:.17g} + {z.imag:.17g}im)"


def _pick_records(path: Path) -> list[dict]:
    out: list[dict] = []
    with gzip.open(path, "rt", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            rec = json.loads(line)
            b = rec.get("bezier", {})
            l = rec.get("linear", {})
            b_steps = float(b.get("total_step_attempts", 0.0))
            l_steps = float(l.get("total_step_attempts", 0.0))
            b_t = float(b.get("tracking_time_sec", 0.0))
            l_t = float(l.get("tracking_time_sec", 0.0))
            if b_steps < l_steps and b_t > l_t:
                rec["_delta_time"] = b_t - l_t
                rec["_delta_steps"] = l_steps - b_steps
                out.append(rec)
    return out


def _write_case_jl(rec: dict, out_path: Path) -> None:
    degree = int(rec["degree"])
    bezier_degree = int(rec["bezier_degree"])
    start = _to_vec(rec["start_coeffs_ri"])
    target = _to_vec(rec["target_coeffs_ri"])
    gamma = _cplx(rec["gamma_ri"])
    ctrl = _to_mat(rec["bezier_control_points_ri"])

    lines: list[str] = []
    lines.append("# Auto-generated by extract_problem_instance.py")
    lines.append(f"# instance_index = {int(rec['instance_index'])}")
    lines.append(f"# delta_time_sec = {float(rec['_delta_time']):.17g}")
    lines.append(f"# delta_steps = {float(rec['_delta_steps']):.17g}")
    lines.append(f"const DEGREE = {degree}")
    lines.append(f"const BEZIER_DEGREE = {bezier_degree}")
    lines.append(f"const GAMMA = {_julia_complex(gamma)}")

    start_str = ", ".join(_julia_complex(z) for z in start)
    target_str = ", ".join(_julia_complex(z) for z in target)
    lines.append(f"const START_COEFFS = ComplexF64[{start_str}]")
    lines.append(f"const TARGET_COEFFS = ComplexF64[{target_str}]")

    # Matrix literal: rows are control points.
    row_exprs = []
    for row in ctrl:
        row_exprs.append("ComplexF64[" + ", ".join(_julia_complex(z) for z in row) + "]")
    lines.append("const BEZIER_CTRL = vcat(" + ", ".join(f"reshape({r}, 1, :)" for r in row_exprs) + ")")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, help="Path to eval_per_instance.jsonl.gz")
    ap.add_argument("--output", required=True, help="Output Julia file path")
    ap.add_argument(
        "--mode",
        choices=["best", "worst"],
        default="best",
        help="best: largest (bezier_time-linear_time), worst: smallest positive gap",
    )
    ap.add_argument(
        "--instance-index",
        type=int,
        default=None,
        help="Pick this instance index directly (must satisfy conditions).",
    )
    args = ap.parse_args()

    in_path = Path(args.input)
    out_path = Path(args.output)
    cand = _pick_records(in_path)
    if not cand:
        raise SystemExit("No candidate found: bezier_steps < linear_steps && bezier_time > linear_time")

    rec = None
    if args.instance_index is not None:
        for c in cand:
            if int(c["instance_index"]) == int(args.instance_index):
                rec = c
                break
        if rec is None:
            raise SystemExit(f"instance_index={args.instance_index} not found in candidate set")
    else:
        cand.sort(key=lambda r: float(r["_delta_time"]), reverse=(args.mode == "best"))
        rec = cand[0]

    _write_case_jl(rec, out_path)
    print(f"wrote {out_path}")
    print(
        f"picked instance_index={int(rec['instance_index'])} "
        f"delta_time={float(rec['_delta_time']):.6f}s "
        f"delta_steps={float(rec['_delta_steps']):.1f}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

